import type { Metadata } from 'next'
import './globals.css'
import { NotificationToast, ClientProvider } from '@/components'
import { getServerSession } from '@/lib/auth'

export const metadata: Metadata = {
  title: 'Next.js Template',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // 서버에서 세션 데이터 조회
  const session = await getServerSession()
  
  return (
    <html lang="en">
      <body>
        <ClientProvider initialUser={session?.user || null}>
          {children}
          <NotificationToast />
        </ClientProvider>
      </body>
    </html>
  )
}